/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BtcTxVerifier__factory } from "./BtcTxVerifier__factory";
export { ERC20__factory } from "./ERC20__factory";
export { Portal__factory } from "./Portal__factory";
